In [7]:
import statistics
import numpy as np
import scipy.stats as stats

In [2]:
li=[1,2,3,3]

In [3]:
statistics.mean(li)

2.25

In [4]:
np.mean(li)

2.25

In [5]:
np.std(li)

0.82915619758885

In [6]:
np.var(li)

0.6875

In [8]:
stats.mode(li)

ModeResult(mode=3, count=2)

In [10]:
one_d=np.random.randint(0,20,20)
one_d

array([17, 14,  5,  0,  0,  1,  8, 16,  9,  6,  8, 11, 11,  3, 10,  6,  0,
       19,  1, 15])

In [11]:
two_d=one_d.reshape(4,5)

In [12]:
two_d

array([[17, 14,  5,  0,  0],
       [ 1,  8, 16,  9,  6],
       [ 8, 11, 11,  3, 10],
       [ 6,  0, 19,  1, 15]])

# obtaining means per row

In [13]:
np.mean(two_d)

8.0

In [14]:
np.mean(two_d,axis=0)

array([ 8.  ,  8.25, 12.75,  3.25,  7.75])

In [15]:
np.mean(two_d,axis=1)

array([7.2, 8. , 8.6, 8.2])

In [2]:
import statistics
import numpy as np
import scipy.stats as stats

In [3]:
two_d=np.arange(1,10).reshape(3,3)

In [4]:
two_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])